on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'


      - name: Install ARM64 cross-compiler
        if: matrix.goarch == 'arm64'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary for ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goarch }}" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
          fi
          CGO_ENABLED=1 GOOS=linux GOARCH=${{ matrix.goarch }} go build -o gql-${{ matrix.goarch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gql-${{ matrix.goarch }}
          path: gql-${{ matrix.goarch }}

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: artifacts


      - name: Archives
        run: |
          for dir in $(find artifacts -mindepth 1 -maxdepth 1 -type d); do
            file=$(ls "$dir")
            chmod +x "$dir/$file"
            tar -czvf "$dir.tar.gz" -C "$dir" "$file"
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
